export { ChatLayout } from './ChatLayout'
export { ChatArea } from './ChatArea'
export { ChatHeader } from './ChatHeader'
export { ChatInput } from './ChatInput'
export { SettingsPanel } from './SettingsPanel'
export { Sidebar } from './Sidebar'
export { SidebarChatHistory } from './SidebarChatHistory'
export { SidebarNavigation } from './SidebarNavigation'
export { SuggestedPrompts } from './SuggestedPrompts'
export { UserFooter } from './UserFooter'

export type { ChatItem } from './SidebarChatHistory'
